### ISSUE TITLE
Windows support issue

### ISSUE THREAD

**Issue by chuong** [GAP-LAB-CUHK-SZ/gaustudio#17]
GauStudio makes use of VDBFusion (for meshing) which is current supported only under Linux.
This is the error when runninng under Windows
`>pip install -r requirements.txt`

`ERROR: Could not find a version that satisfies the requirement vdbfusion (from versions: none)
ERROR: No matching distribution found for vdbfusion`

Not sure if it helps to report this issue here.

**Comment by hugoycj** [comment]
Apologies for the inconvenience. Since we do not have a Windows server available, we were unable to fully test the application on Windows before making changes.

In the development branch, we have replaced the vdbfusion with the Open3D TSDF fusion. You are welcome to try the [release/better-mesh-extraction](https://github.com/GAP-LAB-CUHK-SZ/gaustudio/tree/release/better-mesh-extraction) branch to see if this helps address the issue.

Please let me know if you have any other questions or concerns. I'm happy to provide further assistance.
