### ISSUE TITLE
vdbfusion does not support windows

### ISSUE THREAD

**Issue by warmsnow-sh** [GAP-LAB-CUHK-SZ/gaustudio#21]
The installation package of vdbfusion under pip does not support win platform
Perhaps we need to modify its dependencies to accommodate windows

**Comment by hugoycj** [comment]
Apologies for the inconvenience. Since we do not have a Windows server available, we were unable to fully test the application on Windows before making changes.

In the development branch, we have replaced the vdbfusion with the Open3D TSDF fusion. You are welcome to try the [release/better-mesh-extraction](https://github.com/GAP-LAB-CUHK-SZ/gaustudio/tree/release/better-mesh-extraction) branch to see if this helps address the issue.

Please let me know if you have any other questions or concerns. I'm happy to provide further assistance.

**Comment by warmsnow-sh** [comment]
It has been successfully installed with no errors. By the way, pytorch3D is also troublesome to install on windows. I should use linux after that.
Finally, I am looking forward to your early release of the entire pipeline including training

**Comment by hugoycj** [comment]
Great to hear that! As for the training code, due to a license conflict with the Gaussian splatting implementation, we cannot release the original training code in this repository. We are working hard to rewrite it from scratch for an official release. The target release date would be in late April or early May
